name: PR Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

jobs:
  security-check:
    name: OSV Scanner on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch (HEAD)
        uses: actions/checkout@v4

      - name: Set up Git to access base branch
        run: git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
        
      - name: Run OSV Scanner on PR HEAD
        uses: google/osv-scanner-action/osv-scanner-action@8dded7155905cd666190a12dc9997000e58d163d # v2.0.        
        with:
          scan-args: '. --format json --output head-results.json'
        continue-on-error: true

    
      - name: Checkout base branch (BASE)
        run: |
          git checkout ${{ github.base_ref }}

      - name: Run OSV Scanner on BASE
        uses: google/osv-scanner-action/osv-scanner-action@8dded7155905cd666190a12dc9997000e58d163d # v2.0.        
        with:
          scan-args: '. --format json --output base-results.json'
        continue-on-error: true

     
      - name: Compare results with OSV Reporter
        uses: google/osv-scanner-action/osv-reporter-action@v1.0.0
        with:
          base-results: base-results.json
          head-results: head-results.json
          output-file: osv-diff.json

     
      - name: Upload differential OSV report
        uses: actions/upload-artifact@v4
        with:
          name: osv-diff-report
          path: osv-diff.json
