name: Daily Security Scan

on:
  schedule:
    - cron: '0 2 * * *' 
  workflow_dispatch:   
  
permissions:
  security-events: write
  contents: read
  
jobs:
  osv-scan:
    name: Run OSV Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@8dded7155905cd666190a12dc9997000e58d163d # v2.0.        
        with:
          scan-args: '--format=sarif --output=results.sarif ./app '
        continue-on-error: true
        
      - name: Upload OSV SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  semgrep:
    name: Run Semgrep (Java)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep with Java ruleset
        run: semgrep --config "p/java" --sarif --output semgrep.sarif

      - name: Upload Semgrep SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
